In [2]:
import numpy as np
a=np.array([10,20,30,40,50])
print("One dimensional array:",a)

One dimensional array: [10 20 30 40 50]


In [4]:
import numpy as np
b=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("Two dimensional array:",b)

Two dimensional array: [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [5]:
import numpy as np
c=np.zeros((3,5))
print("\n Array with all zeros:\n",c)


 Array with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
import numpy as np
d=np.random.random((3,3))
print("\n Random value:\n",d)


 Random value:
 [[0.35507195 0.81209456 0.8294121 ]
 [0.77540669 0.63444027 0.34330152]
 [0.32895178 0.86875831 0.01788786]]


In [8]:
import numpy  as np
e=np.arange(0,100,5)
print("\n Range value:\n",e)


 Range value:
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [9]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarr=arr.reshape((4,3))
print("\n Original array:\n",arr)
print("\n Reshaped array [4,3]:\n", newarr)


 Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Reshaped array [4,3]:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
import numpy as np
a=np.zeros((5,3))
b=np.random.random((5,3))
c=np.arange(0,5,3)
d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
flat=d.flatten()
e=d.reshape((3,5))
newtype=d.astype('f')
print("\n convert array element:\n",newtype)
print("datatype of converted array:\n",newtype.dtype)
print("\n Array with all zeros:\n",a)
print("\n Array with random values:\n",b)
print("\n Range value:\n",c)
print("\n orginal array:\n",d)
print("\n Reshaped array [5,3]:\n",e)
print("Flattened array:\n",flat)


 convert array element:
 [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]
datatype of converted array:
 float32

 Array with all zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 Array with random values:
 [[0.88863835 0.69415406 0.77149348]
 [0.90553549 0.13027248 0.50811414]
 [0.49558698 0.53958214 0.66094924]
 [0.40156105 0.57522543 0.98563641]
 [0.86455068 0.2564437  0.67744573]]

 Range value:
 [0 3]

 orginal array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

 Reshaped array [5,3]:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Flattened array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [25]:
import numpy as np
flat=d.flatten()
print("flattened array:\n",flat)

flattened array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [27]:
import numpy as np
b=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("no of dimensional array:",b.ndim)

no of dimensional array: 2


In [31]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print("\n shape of the array:",arr.shape)


 shape of the array: (5, 3)


In [6]:
print("\n Array element type:",arr.dtype)

NameError: name 'arr' is not defined

In [16]:
import numpy as np
d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
newtype=d.astype('f')
print("\n convert array element:\n",newtype)
print("\ndatatype of converted array:",newtype.dtype)


 convert array element:
 [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]

datatype of converted array: float32


In [14]:
import numpy as np
d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
size=len(d)
print("\n size of array:\n",d.size)


 size of array:
 15
